<a href="https://colab.research.google.com/github/PAWAN367457/pawan/blob/master/pytorch_nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, features):

    out = self.network(features)

    return out

In [2]:
# create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call model for forward pass
# model.forward(features)
model(features)

tensor([[0.6071],
        [0.5921],
        [0.5919],
        [0.5951],
        [0.5720],
        [0.5993],
        [0.6051],
        [0.6003],
        [0.6019],
        [0.6032]], grad_fn=<SigmoidBackward0>)

In [5]:
# show model weights
# model.linear2.weight # This caused an error
print("Weights of the first linear layer:")
print(model.network[0].weight)
print("\nWeights of the second linear layer:")
print(model.network[2].weight)

Weights of the first linear layer:
Parameter containing:
tensor([[-0.2566,  0.1719,  0.0196,  0.1154, -0.2062],
        [ 0.0691, -0.2602,  0.3663, -0.0733, -0.0843],
        [-0.4187, -0.4116, -0.4453,  0.2147,  0.3521]], requires_grad=True)

Weights of the second linear layer:
Parameter containing:
tensor([[-0.1288, -0.2872, -0.4173]], requires_grad=True)


In [ ]:
!pip install torchinfo

In [ ]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00